doctrine:
    dbal:
        types:
            phone_number: Misd\PhoneNumberBundle\Doctrine\DBAL\Types\PhoneNumberType
    orm:
        entity_managers:
            default:
                dql:
                    datetime_functions:
                        month: Ekyna\Bundle\CoreBundle\Dql\Month
                        year: Ekyna\Bundle\CoreBundle\Dql\Year
                        day: Ekyna\Bundle\CoreBundle\Dql\Day
                        rand: Ekyna\Bundle\CoreBundle\Dql\Rand
                        unix_timestamp: Ekyna\Bundle\CoreBundle\Dql\UnixTimestamp
