knp_gaufrette:
    adapters:
        local_upload:
            local:
                directory:  "%kernel.root_dir%/../var/upload"
                create:     true
    filesystems:
        local_upload:
            adapter: local_upload
    stream_wrapper: ~