oneup_flysystem:
    adapters:
        local_upload:
            local:
                directory: %kernel.root_dir%/../var/upload
        local_tmp:
            local:
                directory: %kernel.root_dir%/../var/tmp
    filesystems:
        local_upload:
            adapter: local_upload
            alias:   local_upload_filesystem
            mount:   local_upload
        local_tmp:
            adapter: local_tmp
            alias:   local_tmp_filesystem
            mount:   local_tmp
